#!/bin/bash

user=none;
pass=none;
isConnected=0;
userExitCode=0;
passExitCode=0;

function checkConnection() {
    responseCode=`curl --max-redirs 0 --silent --output /dev/null -X "GET" --write-out "%{http_code}" "http://www.cubadebate.cu/"`;
    echo "Connection checking response code: $responseCode"
    isCaptivePortal=`curl --silent -X "GET" "http://www.cubadebate.cu/" | grep "https://secure.etecsa.net" | wc -l`
    if [ "$responseCode" = "200" ] && [ $isCaptivePortal -eq 0 ]; then
      isConnected=1;
    else
      isConnected=0;
    fi 
}

function login() {
  # credentials.txt json is expected to be found on nuta folder inside home folder
  cd ~/nauta;
  i=0;
  while [ $userExitCode -eq 0 ] && [ $passExitCode -eq 0 ]; do
    user=`cat credentials.txt | python3 -c "import sys, json; print(json.load(sys.stdin)[$i]['user'])"`
    userExitCode=$?;
    pass=`cat credentials.txt | python3 -c "import sys, json; print(json.load(sys.stdin)[$i]['pass'])"`
    passExitCode=$?;
    if [ "$user" != "" ] && [ $pass != "" ]; then
    #      echo "Login with User: $user and Pass: $pass";
      curl -s --request POST \
      --url https://secure.etecsa.net:8443//LoginServlet \
      --header 'Content-Type: application/x-www-form-urlencoded' \
      --data username="$user" \
      --data password="$pass" \
      > /dev/null
    else
      return;
    fi 
    ((i+=1));		  		  
  done
}

function start() {
  checkConnection;
  if [ $isConnected -eq 0 ]; then
    echo "Is not connected, requesting nauta login.";
    login;
  else
    echo "Nauta already connected.";
  fi 
  exit;
}

start;