#!/bin/bash

user=none;
pass=none;
userExitCode=0;
passExitCode=0;

login() {
  # credentials.txt json is expected to be found on nuta folder inside home folder
  cd ~/nauta;
  i=0;
  while [ $userExitCode -eq 0 ] && [ $passExitCode -eq 0 ]; do
    user=`cat credentials.txt | python3 -c "import sys, json; print(json.load(sys.stdin)[$i]['user'])"`
    userExitCode=$?;
    pass=`cat credentials.txt | python3 -c "import sys, json; print(json.load(sys.stdin)[$i]['pass'])"`
    passExitCode=$?;
    if [ "$user" != "" ] && [ $pass != "" ]; then
    #      echo "Login with User: $user and Pass: $pass";
      curl -s --request POST \
      --url https://secure.etecsa.net:8443//LoginServlet \
      --header 'Content-Type: application/x-www-form-urlencoded' \
      --data username="$user" \
      --data password="$pass" \
      > /dev/null
    else
      return;
    fi 
    ((i+=1));		  		  
  done
}

login;
